In [1]:
import numpy as np

In [7]:
np.array([4, 5, 6])

array([4, 5, 6])

In [9]:
A = np.array([[4, 5], [5, 6]])

In [13]:
print(A)

[[4 5]
 [5 6]]


In [18]:
a = np.array([20, 30, 40, 50])
b = np.array([0,1, 2, 3, 4])

In [30]:
A*0

array([[0, 0],
       [0, 0]])

In [35]:
np.ones((3, 3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [40]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [49]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
A

array([[4, 5],
       [5, 6]])

In [68]:
nums = np.arange(0, 500, 1)

In [69]:
nums

array([  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
        13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
        26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
        39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,
        52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,
        65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,
        78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,
        91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102, 103,
       104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115, 116,
       117, 118, 119, 120, 121, 122, 123, 124, 125, 126, 127, 128, 129,
       130, 131, 132, 133, 134, 135, 136, 137, 138, 139, 140, 141, 142,
       143, 144, 145, 146, 147, 148, 149, 150, 151, 152, 153, 154, 155,
       156, 157, 158, 159, 160, 161, 162, 163, 164, 165, 166, 167, 168,
       169, 170, 171, 172, 173, 174, 175, 176, 177, 178, 179, 18

In [71]:
np.sum(nums)

124750

In [77]:
np.sum(nums[0:499:2])

62250

In [83]:
np.sum(nums[1:500:2])

62500

In [87]:
I = np.eye(4)
I

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [88]:
np.size(I)

16

In [91]:
np.random.randint(2, 9, 3)

array([2, 8, 5])

In [116]:
M = np.random.randint(0, 5, 
    (np.random.randint(1,10),np.random.randint(1,10)))

In [117]:
M

array([[1, 2, 0, 2, 1, 0, 4, 1, 0],
       [4, 2, 4, 1, 2, 2, 3, 4, 2],
       [2, 3, 1, 3, 2, 2, 2, 2, 0],
       [0, 0, 3, 0, 4, 4, 3, 1, 3],
       [1, 0, 2, 2, 3, 0, 2, 4, 2],
       [3, 3, 0, 1, 1, 1, 2, 0, 4],
       [4, 4, 3, 1, 3, 3, 1, 3, 2],
       [0, 0, 4, 1, 0, 4, 2, 2, 4],
       [1, 4, 0, 1, 3, 2, 0, 3, 0]])

In [121]:
x = np.array([2,3])
y = np.array([1,1])
x, y

(array([2, 3]), array([1, 1]))

In [122]:
T = np.array([[1, 2], [0, 1]])
T

array([[1, 2],
       [0, 1]])

In [123]:
T * x

array([[2, 6],
       [0, 3]])

In [129]:
np.dot(x, y)

5

In [133]:
np.linalg.norm(x)  # || x ||

3.605551275463989

In [134]:
np.linalg.norm(y)

1.4142135623730951

In [135]:
theta = 60.0
R = np.array([[np.cos(theta), -np.sin(theta)], 
              [np.sin(theta), np.cos(theta)]])

In [136]:
R

array([[-0.95241298,  0.30481062],
       [-0.30481062, -0.95241298]])

In [138]:
np.matmul(R, x)

array([-0.9903941 , -3.46686018])

In [139]:
np.dot(R, x)

array([-0.9903941 , -3.46686018])

In [141]:
np.matmul(T, x)

array([8, 3])

In [143]:
t = np.array([2, 3])
zero = np.array([0, 0])
I = np.eye(2)

In [150]:
T = np.array([[I, t.T], [zero.T, 1]])

In [152]:
T

array([[array([[1., 0.],
       [0., 1.]]), array([2, 3])],
       [array([0, 0]), 1]], dtype=object)

In [155]:
T = np.ones((3, 3))
T

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [157]:
T

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [158]:
A = np.array([[1, 3, -1], [2, 0, -1], [0, -2, 1]])

In [166]:
B = np.array([[0, -1, 1], [1, 3, 0], [1, -2, 4]])

In [167]:
print(A)

[[ 1  3 -1]
 [ 2  0 -1]
 [ 0 -2  1]]


In [168]:
print(B)

[[ 0 -1  1]
 [ 1  3  0]
 [ 1 -2  4]]


In [169]:
C = A * B
print(C)

[[ 0 -3 -1]
 [ 2  0  0]
 [ 0  4  4]]


In [174]:
C_last = C[2:3,0]
print(C_last)

[0]


In [176]:
#C[start:end, start:end]

In [201]:
C[1] = np.ones(3) * 400

In [204]:
D = np.dot(B, C)
D

array([[-400, -396, -400],
       [1200, 1197, 1199],
       [-800, -787, -801]])

In [206]:
D[0:2, 1:3]

array([[-396, -400],
       [1197, 1199]])

In [207]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [236]:
x[::-3]

array([9, 6, 3, 0])

In [244]:
np.arange(1,5, .1)

array([1. , 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9, 2. , 2.1, 2.2,
       2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9, 3. , 3.1, 3.2, 3.3, 3.4, 3.5,
       3.6, 3.7, 3.8, 3.9, 4. , 4.1, 4.2, 4.3, 4.4, 4.5, 4.6, 4.7, 4.8,
       4.9])

In [245]:
A * B

array([[ 0, -3, -1],
       [ 2,  0,  0],
       [ 0,  4,  4]])

In [246]:
np.matmul(A, B)

array([[ 2, 10, -3],
       [-1,  0, -2],
       [-1, -8,  4]])

In [249]:
np.linalg.inv(A)

array([[ 0.5 ,  0.25,  0.75],
       [ 0.5 , -0.25,  0.25],
       [ 1.  , -0.5 ,  1.5 ]])

In [253]:
np.savetxt('A.txt', A)